### PR TITLE
SEQNG-398: Update layout

### PR DESCRIPTION
**Pull request by cquiroz**
After some discussion we are considering to update the layout of the application. We want to better use the space removing the width restrictions and vertical layers

This PR is not final, it needs a lot of polishing but I wanted to show it to get comments.

The main changes are:
* Use of the full width of the browser
* Removal of titles to gain vertical space
* Reduce nesting of sections
* Move headers section next to the queue area
* Remove top bar and replace it with a status bar at the bottom

Here's a screenshot. Let me know what you think before I can continue

https://monosnap.com/file/JsNR3B1XcpG1T77fzjdKVc0Qg1FSkg

### CODE REVIEW

**Comment by andrewwstephens** [comment]
Looks good to me.
Should the tabs be made wider?

**Comment by bryanmiller** [comment]
Yes, much better.

**Comment by arturog8m** [comment]
Gorgeous!

**Comment by cquiroz** [comment]
After some changes to adjust the layout here's my final version

https://monosnap.com/file/ZtH0N5sDFWWfX399sv2EfnANf8lAy7

I suppose there are details to still work out but this seems workable

**Pull request merged**
