### PR TITLE
SEQNG-244: Add urls to instrument tabs

### PR DESCRIPTION
**Pull request by cquiroz**
Sorry for the size of this PR. It started as adding urls to instrument tabs using React's router facility but it kept growing as I did some learnings and realized that I had to refactor quite a bit

I did some small changes to improve the look when having multiple observations on the queue

This change is fairly large and created some regressions which have been reported but will be fixed in separate PRs

screenshot 2017-06-29 15 47 34

### CODE REVIEW

**Comment by jdnavarro** [comment]
This is a huge PR, so it's going to take some time to review. Are you in a hurry to merge?

**Comment by cquiroz** [comment]
It is very big as you said and it is difficult to understand what it does from the diff. I'm basing my new work on this PR but there is no great hurry

**Comment by jluhrs** [comment]
I'm afraid only @cquiroz can fully understand all the changes. At least I am lacking a lot of background to be able to review them. So, how do we procede? Just approve the changes and trust that Carlos didn't make any mistake?

**Comment by cquiroz** [comment]
Unfortunately UI code is very difficult to read and get what it does in your mind. I'm not sure if I could parse it so easily either. In this PR is even worse as the changes are deep

At least a sanity check that the application runs would be useful

**Comment by jdnavarro** [comment]
> At least a sanity check that the application runs would be useful

I'm on it.

**Comment by jdnavarro** [comment]
I've been toying with the UI and it all seems to be working nicely. The URLs are updating accordingly and the focus switches to the tab instrument when clicking on the sequence. Great job 👍

**Comment by cquiroz** [comment]
Thanks a lot

**Pull request merged**
