### PR TITLE
smaller build steps

### PR DESCRIPTION
**Pull request by tpolecat**
Messing around with the build script. I'm thinking maybe breaking it up into smaller steps will make it more reliable.

### CODE REVIEW

**Comment by tpolecat** [comment]
This increases the build time by like 30 seconds but it seems to be more stable, at least relative to earlier today. I ran it 10 times and it failed twice.

**Comment by cquiroz** [comment]
Seems good, 30s sounds worth more stability

**Comment by tpolecat** [comment]
This also moves the pipeline definition to a YAML file which allows us to specify retries (set to 2 for now).

**Comment by tpolecat** [comment]
@cquiroz can you approve this? I think it's worth doing.

**Pull request merged**
