### PR TITLE
Use typelevel scala compiler

### PR DESCRIPTION
**Pull request by cquiroz**
Let's use the typelevel compiler along the gem project

### CODE REVIEW

**Comment by jdnavarro** [comment]
I can't compile it in my machine because some typelevel dependencies can't be found. Does this need some global configuration for `sbt`?

**Comment by cquiroz** [comment]
Not really, sounds like an issue on your local machine? Perhaps a confused ivy repo?

**Comment by jdnavarro** [comment]
I nuked my `.ivy2` and `.m2` dirs and commented out all my sbt global configuration but still getting the same unresolved dependencies:

 - `org.scala-lang#scala-reflect;2.11.11-bin-typelevel-4`
 - `org.scala-lang#scala-compiler;2.11.11-bin-typelevel-4`

**Comment by cquiroz** [comment]
Found some issues on this, and will rework it. I'm quite surprised that travis accepted id

**Pull request closed without merging**
