### PR TITLE
SEQNG-169: GCAL FITS keywords

### PR DESCRIPTION
**Pull request by cquiroz**
Implementation of the Gcal keywords

### CODE REVIEW

**Comment by jluhrs** [comment]
Almost there. The one issue is something I forgot to put in the task description. The GCAL keywords are optional, they are written only for calibration steps. Therefore, they should not be in StandardHeader, but in its own Header, and added to the list of headers written for `FlatOrArc` in `calcHeaders`

**Comment by cquiroz** [comment]
should the keywords be sent before or after as per the methods in `Header`?

**Comment by cquiroz** [comment]
Updated according to the PR comments

**Comment by cquiroz** [comment]
@jluhrs Would you be able to validate this with GCAL once merged?

**Comment by jluhrs** [comment]
Yes, I'll create a task to test this and my PR against the real systems.

**Pull request merged**
