### PR TITLE
SEQNG-1167: Hearbeart log message is not shown in client

### PR DESCRIPTION
**Pull request by cquiroz**
It was requested that we should hearbeat messages in the client.
I don't like this feature at all but it is implemented here
It pollutes the client log and makes it note very useful
We should first fix the freezing bug or leave the messages server only
image (4)

### CODE REVIEW

**Comment by andrewwstephens** [comment]
This is the inverse of what we want to know (like a fire alarm that beeps when there is no fire).  Is there any (easy) way to throw a warning when the seqexec server stops responding to queries?

**Comment by cquiroz** [comment]
If we were able to know that we'd probably fix the bug 😄

**Comment by jluhrs** [comment]
Maybe we could add some processing in the web server that would filter these messages, but generate a different one if it doesn't see a heartbeat in, say, 30 s?

**Comment by cquiroz** [comment]
I updated this PR to use the new heartbeat system, and we only get notified if the heart beat is lost
Seqexec - GS 2020-01-08 20-34-49

**Pull request merged**
