### PR TITLE
SEQNG-971 Improved robustness of audio play in Linux

### PR DESCRIPTION
**Pull request by cquiroz**
Sound and linux don't mix well. This PR improves robustness by delivering webm versions of the files too

It will also play a sound when the sound on button is activated
image

Tested on:
* FF ESR 60.0.2 on CentOS 7 running on VMWare
* Chrome 73 on CentOS 7 running on VMWare
* FF 66.0.2 on OSX Mojave
* Chrome 73 on OSX Mojave
* Safari 12.1 on OSX Mojave
* iOS Safari 12.1 on an iPad 2018
* iOS FF 15.1 on an iPad 2019
* iOS Chrome 73 on an iPad 2018

### CODE REVIEW

**Comment by tpolecat** [comment]
What year is it again?

**Comment by cquiroz** [comment]
2019 is the year of the linux desktop

**Comment by sraaphorst** [comment]
I thought 1999 was the year of the Linux desktop?

**Comment by cquiroz** [comment]
Next year is ALWAYS the year of the Linux desktop

**Pull request merged**
